### ISSUE TITLE
test_euler_estimator.py comments

### ISSUE THREAD

**Issue by charlieweinberger** [JHpusd/simulation#2]
You didn't have to comment out the old tests (for the second comment) for the plot() method to still work. This is probably jut my opinion. Also, you probably won't need the tests from the single-variable Euler Estimator (in the first comment).

**Comment by jyhong05** [comment]
I usually comment out old tests, just for the sake of cleanliness and making the code go a tiny bit faster. (It's much more apparent if the function is recursive or I'm using matplotlib)
