### ISSUE TITLE
Minor shortening 

### ISSUE THREAD

**Issue by snowthesprite** [JHpusd/simulation#4]
In your `calc_estimated_points` you can initialize `point_list` with `point`, so that you don't have to append it, and replace `next_point` with `point` or initalize `next_point = point` before the loop so that you don't have that `point = next_point`. 

I honestly made this an issue because I need two and any other issues I could find had already been dinged. It looks pretty good and readable to me!

But you should just use  `calc_estimated_points` in `plot`. It both shortens the code and makes it easier to see what your doing.

**Comment by jyhong05** [comment]
Thanks, I fixed both.
