### ISSUE TITLE
possible generalization in predator_prey_model.py

### ISSUE THREAD

**Issue by charlieweinberger** [JHpusd/simulation#5]
In you predator_prey_model.py code, you mention the wolf and the deer. You can generalize this to symbolize interactions between different predators and preys. You can do this by changing all of the 'wolf' variable names to 'predator' and all of the 'deer' predator names to 'prey'.

**Comment by jyhong05** [comment]
Thanks, but I believe that this specific model was made for wolves and deer specifically. You never know what might change the system -- be it a change in animals, conditions, etc.
