### ISSUE TITLE
More versatility in euler estimator

### ISSUE THREAD

**Issue by jyhong05** [JHpusd/simulation#7]
Add a way to change the legend labels and location of the legend in the plot method.

**Comment by JHpusd** [comment]
I was able to add legend location, but the labels are a bit hard to change, since they are taken directly from the point itself.

**Comment by jyhong05** [comment]
I was able to change the legend location, but it is a bit difficult to make legend labels without cluttering up the code, and taking the  labels directly from the point is the most efficient way to get the labels.
