### ISSUE TITLE
Rename variable

### ISSUE THREAD

**Issue by walliuswilliam** [JHpusd/simulation#8]
On line 37 in your euler estimator, the 't_list' variable is a little confusing on what it is. Since it is your x_values for your graph, i would recommend naming it as such, though you may have a reason that is clear that im not seeing.

**Comment by jyhong05** [comment]
I believe that the points entered into the euler estimator points are in the format (t,x) where x is the dictionary of values. And I set t_list equal to the list of t-values (the first entry of each point). It may be the x value, but the euler estimator graphs are usually interpreted as time vs (variables).
